# Generated by Django 2.1.8 on 2019-04-17 09:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='identifier',
            field=models.CharField(default=123, max_length=40, unique=True),
            preserve_default=False,
        ),
    ]
